# Alternative Docker Compose with Docker Secrets (Production)
# Use this instead of docker-compose.yml for production with proper secrets management

version: '3.8'

services:
  schoology-scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    image: schoology-scraper:latest
    container_name: schoology-scraper
    
    # Environment variables (non-sensitive only)
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    
    # Volume mounts for data persistence and configuration
    volumes:
      # Data persistence
      - ./data:/app/data
      - ./logs:/app/logs
      
      # Configuration (non-sensitive)
      - ./config.toml:/app/config.toml:ro
    
    # Docker secrets (mounted at /run/secrets/)
    secrets:
      - google_email
      - google_password
      - aws_access_key
      - aws_secret_key
      - pushover_token
      - pushover_userkey
      - gemini_key
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true

# Docker secrets definition
secrets:
  google_email:
    file: ./secrets/google_email.txt
  google_password:
    file: ./secrets/google_password.txt
  aws_access_key:
    file: ./secrets/aws_access_key.txt
  aws_secret_key:
    file: ./secrets/aws_secret_key.txt
  pushover_token:
    file: ./secrets/pushover_token.txt
  pushover_userkey:
    file: ./secrets/pushover_userkey.txt
  gemini_key:
    file: ./secrets/gemini_key.txt

# To use this secrets-based approach:
# 1. Create secrets/ directory: mkdir -p secrets
# 2. Create individual secret files:
#    echo "your-google-email@gmail.com" > secrets/google_email.txt
#    echo "your-password" > secrets/google_password.txt
#    # ... etc for each secret
# 3. Secure the secrets directory: chmod 700 secrets && chmod 600 secrets/*
# 4. Run with: docker-compose -f docker-secrets.yml up